baseURL = 'https://ebribi.github.io/linuxnoob/'
languageCode = 'en-us'
title = 'Linux Noob'
theme="Xmin"
[[menu.main]]
name = "Home"
url =  "/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
